In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('medium_data.csv')
df.head()

,id,url,title,subtitle,image,claps,responses,reading_time,publication,date
0,1,https://towardsdatascience.com/a-beginners-gui...,A Beginner’s Guide to Word Embedding with Gens...,NaN,1.png,850,8,8,Towards Data Science,2019-05-30
1,2,https://towardsdatascience.com/hands-on-graph-...,Hands-on Graph Neural Networks with PyTorch & ...,NaN,2.png,1100,11,9,Towards Data Science,2019-05-30
2,3,https://towardsdatascience.com/how-to-use-ggpl...,How to Use ggplot2 in Python,A Grammar of Graphics for Python,3.png,767,1,5,Towards Data Science,2019-05-30
3,4,https://towardsdatascience.com/databricks-how-...,Databricks: How to Save Files in CSV on Your L...,When I work on Python projects dealing…,4.jpeg,354,0,4,Towards Data Science,2019-05-30
4,5,https://towardsdatascience.com/a-step-by-step-...,A Step-by-Step Implementation of Gradient Desc...,One example of building neural…,5.jpeg,211,3,4,Towards Data Science,2019-05-30


In [3]:
# for i in df['title']:
#     print(i)
#     print('*******************************************************************')

In [3]:
df.shape

(6508, 10)

In [5]:
doc= '\n'.join(df['title'].sample(1000))
# print(doc)

In [6]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:
tokenizer = Tokenizer()

In [8]:
tokenizer.fit_on_texts([doc.lower()])

In [9]:
tokenizer.word_index
    

{'to': 1,
 'the': 2,
 'strong': 3,
 'a': 4,
 'how': 5,
 'of': 6,
 'your': 7,
 'and': 8,
 'markup': 9,
 'in': 10,
 'for': 11,
 'with': 12,
 'you': 13,
 'is': 14,
 'why': 15,
 'data': 16,
 'class': 17,
 'h3': 18,
 'i': 19,
 'what': 20,
 'an': 21,
 'are': 22,
 'be': 23,
 'on': 24,
 'can': 25,
 'learning': 26,
 'ux': 27,
 'do': 28,
 'not': 29,
 'using': 30,
 'when': 31,
 'from': 32,
 'writing': 33,
 'about': 34,
 'my': 35,
 'we': 36,
 'more': 37,
 'it': 38,
 'first': 39,
 '5': 40,
 'that': 41,
 'make': 42,
 'design': 43,
 '3': 44,
 'or': 45,
 'as': 46,
 'life': 47,
 'should': 48,
 'python': 49,
 'up': 50,
 'will': 51,
 'ai': 52,
 'science': 53,
 'need': 54,
 'into': 55,
 'machine': 56,
 'get': 57,
 'ways': 58,
 'don’t': 59,
 'tips': 60,
 'simple': 61,
 'at': 62,
 'best': 63,
 'great': 64,
 'know': 65,
 'stop': 66,
 'being': 67,
 'three': 68,
 'use': 69,
 'product': 70,
 'by': 71,
 'top': 72,
 'better': 73,
 'making': 74,
 'write': 75,
 'new': 76,
 'have': 77,
 'work': 78,
 'digital': 79,
 

In [10]:
print(len(tokenizer.word_index
         ))

2889


In [11]:
input_sequences=[] 
for i in df['title']:
    tokenized_sentence = tokenizer.texts_to_sequences([i])[0]

    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])



In [12]:
input_sequences

[[4, 512],
 [4, 512, 94],
 [4, 512, 94, 1],
 [4, 512, 94, 1, 1844],
 [4, 512, 94, 1, 1844, 1224],
 [4, 512, 94, 1, 1844, 1224, 12],
 [24, 138],
 [24, 138, 181],
 [24, 138, 181, 12],
 [24, 138, 181, 12, 332],
 [24, 138, 181, 12, 332, 332],
 [5, 1],
 [5, 1, 69],
 [5, 1, 69, 230],
 [5, 1],
 [5, 1, 680],
 [5, 1, 680, 449],
 [5, 1, 680, 449, 10],
 [5, 1, 680, 449, 10, 1205],
 [5, 1, 680, 449, 10, 1205, 24],
 [5, 1, 680, 449, 10, 1205, 24, 7],
 [4, 119],
 [4, 119, 71],
 [4, 119, 71, 119],
 [4, 119, 71, 119, 552],
 [4, 119, 71, 119, 552, 6],
 [4, 119, 71, 119, 552, 6, 8],
 [4, 119, 71, 119, 552, 6, 8, 1535],
 [21, 189],
 [21, 189, 88],
 [21, 189, 88, 1],
 [21, 189, 88, 1, 509],
 [21, 189, 88, 1, 509, 11],
 [21, 189, 88, 1, 509, 11, 16],
 [21, 189, 88, 1, 509, 11, 16, 186],
 [88, 1],
 [88, 1, 542],
 [88, 1, 542, 1301],
 [88, 1, 542, 1301, 1300],
 [88, 1, 542, 1301, 1300, 1273],
 [562, 455],
 [562, 455, 1246],
 [562, 455, 1246, 14],
 [562, 455, 1246, 14, 2],
 [562, 455, 1246, 14, 2, 63],
 [562,

In [13]:
max_len = max([len(x) for x in input_sequences])
max_len

27

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [15]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   4, 512],
       [  0,   0,   0, ...,   4, 512,  94],
       [  0,   0,   0, ..., 512,  94,   1],
       ...,
       [  0,   0,   0, ...,   1,  75,   4],
       [  0,   0,   0, ...,  75,   4, 191],
       [  0,   0,   0, ...,   4, 191,  81]], dtype=int32)

In [15]:
# padded_input_sequences[:,:-1]

In [16]:
X = padded_input_sequences[:,:-1]

In [17]:
y = padded_input_sequences[:,-1]

In [50]:
X[0].size

26

In [18]:
y

array([512,  94,   1, ...,   4, 191,  81], dtype=int32)

In [19]:
print(X.shape)
print(y.shape)

(31505, 26)
(31505,)


In [20]:
len(tokenizer.word_index)

2889

In [21]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=2890)

In [22]:
print(y.shape)

(31505, 2890)


In [23]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Input

model = Sequential()
model.add(Input(shape=(26,)))
model.add(Embedding(2890, 100))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(150))
model.add(Dense(2890, activation='softmax'))

model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 26, 100)             │         289,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 26, 150)             │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 2890)                │         436,390 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,056,590 (4.03 MB)

 Trainable params: 1,056,590 (4.03 MB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 26, 100)             │         289,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 26, 150)             │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 2890)                │         436,390 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,056,590 (4.03 MB)

 Trainable params: 1,056,590 (4.03 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X,y,epochs=1)

985/985 ━━━━━━━━━━━━━━━━━━━━ 34s 31ms/step - accuracy: 0.0854 - loss: 6.0781


In [36]:
txt = 'matrix'
# tokenize
token_text = tokenizer.texts_to_sequences([txt])[0]
# padding
padded_token_text = pad_sequences([token_text],maxlen=27,padding='pre')
print(padded_token_text)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0 542]]


In [37]:
model.predict(padded_token_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[1.0034900e-05, 1.5667416e-02, 3.1509463e-02, ..., 6.0785271e-05,
        5.2908574e-05, 7.3281357e-05]], dtype=float32)

In [38]:
model.predict(padded_token_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


(1, 2890)

In [42]:
pos = np.argmax(model.predict(padded_token_text))
pos

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step


np.int64(2)

In [43]:
for word,index in tokenizer.word_index.items():
    if index==pos:
        print(word)

the


In [47]:
# multiple words


txt = 'nlp'
for i in range(5):
    # tokenize
    token_text = tokenizer.texts_to_sequences([txt])[0]
    # padding
    padded_token_text = pad_sequences([token_text],maxlen=27,padding='pre')
    # print(padded_token_text)
    # return the position that have a high probability
    pos = np.argmax(model.predict(padded_token_text))

    for word,index in tokenizer.word_index.items():
        if index==pos: 
            txt = txt + " " + word
            print(txt)
        
    


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
nlp a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
nlp a the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
nlp a the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
nlp a the the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
nlp a the the the the
