In [88]:
import numpy as np
import pandas as pd

In [89]:
df = pd.read_csv('medium_data.csv')
df.head()

,id,url,title,subtitle,image,claps,responses,reading_time,publication,date
0,1,https://towardsdatascience.com/a-beginners-gui...,A Beginner’s Guide to Word Embedding with Gens...,NaN,1.png,850,8,8,Towards Data Science,2019-05-30
1,2,https://towardsdatascience.com/hands-on-graph-...,Hands-on Graph Neural Networks with PyTorch & ...,NaN,2.png,1100,11,9,Towards Data Science,2019-05-30
2,3,https://towardsdatascience.com/how-to-use-ggpl...,How to Use ggplot2 in Python,A Grammar of Graphics for Python,3.png,767,1,5,Towards Data Science,2019-05-30
3,4,https://towardsdatascience.com/databricks-how-...,Databricks: How to Save Files in CSV on Your L...,When I work on Python projects dealing…,4.jpeg,354,0,4,Towards Data Science,2019-05-30
4,5,https://towardsdatascience.com/a-step-by-step-...,A Step-by-Step Implementation of Gradient Desc...,One example of building neural…,5.jpeg,211,3,4,Towards Data Science,2019-05-30


In [90]:
doc = '\n'.join(df['title'].str.lower())


In [91]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [92]:
tokenizer = Tokenizer()
# tokenizer.fit_on_texts([doc])

In [93]:
tokenizer.fit_on_texts([doc])


In [94]:
tokenizer.word_index

{'to': 1,
 'the': 2,
 'strong': 3,
 'a': 4,
 'how': 5,
 'of': 6,
 'and': 7,
 'markup': 8,
 'your': 9,
 'in': 10,
 'for': 11,
 'you': 12,
 'is': 13,
 'with': 14,
 'class': 15,
 'h3': 16,
 'why': 17,
 'data': 18,
 'i': 19,
 'what': 20,
 'on': 21,
 'from': 22,
 'an': 23,
 'learning': 24,
 'can': 25,
 'are': 26,
 'my': 27,
 'be': 28,
 'using': 29,
 'do': 30,
 'ux': 31,
 'design': 32,
 'not': 33,
 'when': 34,
 'writing': 35,
 'that': 36,
 'we': 37,
 'about': 38,
 '5': 39,
 'machine': 40,
 'make': 41,
 'it': 42,
 'should': 43,
 'as': 44,
 'need': 45,
 'ai': 46,
 '3': 47,
 'more': 48,
 'don’t': 49,
 'life': 50,
 'marketing': 51,
 'or': 52,
 'will': 53,
 'have': 54,
 'ways': 55,
 'get': 56,
 'time': 57,
 'at': 58,
 'up': 59,
 'guide': 60,
 'science': 61,
 'use': 62,
 'by': 63,
 'write': 64,
 'business': 65,
 'new': 66,
 'python': 67,
 'if': 68,
 'deep': 69,
 'self': 70,
 'best': 71,
 'first': 72,
 'into': 73,
 'top': 74,
 'tips': 75,
 'things': 76,
 'stop': 77,
 'analysis': 78,
 'intelligence'

In [95]:
print(len(tokenizer.word_index
         ))

10969


In [98]:
input_sequences=[]
for i in df['title']:
    tokenized_sentence = tokenizer.texts_to_sequences([i])[0]
    # print(tokenized_sentence)


    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

input_sequences


[[4, 565],
 [4, 565, 60],
 [4, 565, 60, 1],
 [4, 565, 60, 1, 434],
 [4, 565, 60, 1, 434, 1309],
 [4, 565, 60, 1, 434, 1309, 14],
 [4, 565, 60, 1, 434, 1309, 14, 3507],
 [4, 565, 60, 1, 434, 1309, 14, 3507, 3508],
 [3509, 21],
 [3509, 21, 782],
 [3509, 21, 782, 111],
 [3509, 21, 782, 111, 157],
 [3509, 21, 782, 111, 157, 14],
 [3509, 21, 782, 111, 157, 14, 477],
 [3509, 21, 782, 111, 157, 14, 477, 477],
 [3509, 21, 782, 111, 157, 14, 477, 477, 1650],
 [5, 1],
 [5, 1, 62],
 [5, 1, 62, 3510],
 [5, 1, 62, 3510, 192],
 [3511, 5],
 [3511, 5, 1],
 [3511, 5, 1, 231],
 [3511, 5, 1, 231, 1073],
 [3511, 5, 1, 231, 1073, 10],
 [3511, 5, 1, 231, 1073, 10, 2216],
 [3511, 5, 1, 231, 1073, 10, 2216, 21],
 [3511, 5, 1, 231, 1073, 10, 2216, 21, 9],
 [3511, 5, 1, 231, 1073, 10, 2216, 21, 9, 3512],
 [4, 169],
 [4, 169, 63],
 [4, 169, 63, 169],
 [4, 169, 63, 169, 398],
 [4, 169, 63, 169, 398, 6],
 [4, 169, 63, 169, 398, 6, 3513],
 [4, 169, 63, 169, 398, 6, 3513, 2217],
 [4, 169, 63, 169, 398, 6, 3513, 2217

In [99]:
max_len = max([len(x) for x in input_sequences])
max_len

38

In [100]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [101]:
padded_input_sequences

array([[    0,     0,     0, ...,     0,     4,   565],
       [    0,     0,     0, ...,     4,   565,    60],
       [    0,     0,     0, ...,   565,    60,     1],
       ...,
       [    0,     0,     0, ...,    64,     4,   104],
       [    0,     0,     0, ...,     4,   104,    65],
       [    0,     0,     0, ...,   104,    65, 10969]], dtype=int32)

In [103]:
X = padded_input_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,   4],
       [  0,   0,   0, ...,   0,   4, 565],
       [  0,   0,   0, ...,   4, 565,  60],
       ...,
       [  0,   0,   0, ...,   1,  64,   4],
       [  0,   0,   0, ...,  64,   4, 104],
       [  0,   0,   0, ...,   4, 104,  65]], dtype=int32)

In [104]:
y = padded_input_sequences[:,-1]
y

array([  565,    60,     1, ...,   104,    65, 10969], dtype=int32)

In [105]:
print(X.shape)

(43439, 37)


In [106]:
print(y.shape)

(43439,)


In [107]:
len(tokenizer.word_index)

10969

In [108]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=10970)

In [109]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [112]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,Input

In [113]:
model = Sequential()
model.add(Input(shape=(37,)))
model.add(Embedding(10970, 100))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(150))
model.add(Dense(10970, activation='softmax'))

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 37, 100)             │       1,097,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 37, 150)             │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 10970)               │       1,656,470 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,084,670 (11.77 MB)

 Trainable params: 3,084,670 (11.77 MB)

 Non-trainable params: 0 (0.00 B)

In [114]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])