In [1]:
import numpy as np
import pandas as  pd

In [2]:
df=pd.read_csv('Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [3]:
df=df.iloc[:,3:]
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [4]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [5]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [6]:
df=pd.get_dummies(df,columns=['Gender','Geography'],drop_first=True)

In [7]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
st=StandardScaler()
x_scaled=st.fit_transform(x)
x_scaled

array([[-0.32622142,  0.29351742, -1.04175968, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.09598752,
        -0.57873591,  1.74273971],
       [-1.53679418,  0.29351742,  1.03290776, ..., -1.09598752,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.91241915,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -1.09598752,
        -0.57873591, -0.57380915]])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.20,random_state=1)

In [12]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(8000, 11) (8000,)
(2000, 11) (2000,)


In [13]:
# pip install tensorflow

In [14]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [64]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


C:\Users\cipl\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [66]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [111]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [115]:
model.fit(x_train,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8673 - loss: 0.3187 - val_accuracy: 0.8637 - val_loss: 0.3172
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8671 - loss: 0.3138 - val_accuracy: 0.8625 - val_loss: 0.3209
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8634 - loss: 0.3291 - val_accuracy: 0.8612 - val_loss: 0.3206
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8654 - loss: 0.3193 - val_accuracy: 0.8656 - val_loss: 0.3215
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8611 - loss: 0.3273 - val_accuracy: 0.8662 - val_loss: 0.3241
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8656 - loss: 0.3232 - val_accuracy: 0.8650 - val_loss: 0.3230
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8695 - loss: 0.3160 - val_accuracy: 0.8650 - val_loss: 0.3235
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8697 - loss: 0.3175 - val_accu

In [117]:
model.layers[0].get_weights()

[array([[ 3.7025280e-02, -1.6333276e-01, -1.6826591e-01, -7.4351251e-01,
          2.7645642e-01,  1.5543716e-01,  1.2055179e-02, -6.5641850e-01,
         -9.1095082e-02,  1.5259841e-01,  3.4790862e-01],
        [-8.0952233e-01, -1.4341806e-01,  5.0350361e-02,  3.2314232e-01,
         -5.9810257e-01,  2.9359883e-01,  6.7998540e-01,  7.5752079e-02,
         -2.6362345e-01,  5.4898745e-01,  1.3111413e-02],
        [ 5.5344374e-04,  1.2752075e-01,  8.2477458e-02,  6.2868595e-01,
         -2.6703796e-01, -9.3192473e-02,  1.0830990e-01, -2.7012303e-01,
         -3.1691605e-01,  3.6875996e-01, -1.8416055e-01],
        [-5.4099159e-03, -9.4469333e-01, -7.8838795e-02, -9.3519293e-02,
         -3.5407093e-01,  3.8209149e-01,  7.4935961e-03,  6.6858083e-01,
          4.2483512e-02, -7.8756720e-01,  3.4152374e-01],
        [-4.1121542e-02, -3.6043537e-01, -1.3704913e+00, -1.7787513e-01,
         -2.5347066e-01,  1.1008704e+00,  4.4614058e-02, -2.2277167e-02,
         -3.0212262e-01, -6.9359589e-0

In [119]:
model.layers[1].get_weights()

[array([[-0.93161535,  0.3915667 , -0.6372322 , -0.27374598, -1.5625057 ,
          0.09459934, -0.3043398 ,  0.25855926,  0.432636  ,  0.33230022,
         -0.02248659],
        [ 0.26511928, -0.32362717,  0.10908853,  0.17717032,  0.15480343,
         -0.7349019 ,  0.01931904,  0.56569946,  0.73372304,  0.6509644 ,
         -0.36233455],
        [ 0.38850263, -0.30727506,  0.38177493,  0.13891087,  0.06319427,
          0.46286973, -0.00815521, -0.45916626, -0.0668764 , -1.5548651 ,
         -0.50599027],
        [ 0.34508464,  0.14167294, -0.7719561 , -0.05031357, -0.07030387,
         -0.5698186 ,  0.24659102, -0.28110492,  0.16603099, -0.7588306 ,
          0.23253554],
        [ 0.2932517 ,  0.05355064,  0.287857  ,  0.58741635,  0.09119312,
         -0.3814531 ,  0.9030138 ,  0.7217907 ,  0.24207175, -0.03276134,
          0.29645517],
        [ 0.5738595 ,  0.5756864 , -0.57250196,  0.7145535 ,  0.30851737,
          0.9324289 , -0.07318814, -1.521544  ,  0.0697742 ,  0.1741045

In [121]:
model.layers[2].get_weights()

[array([[ 1.3771585 ],
        [ 1.6621319 ],
        [ 1.120249  ],
        [ 0.5713571 ],
        [ 0.9088976 ],
        [ 0.59604484],
        [-1.4832458 ],
        [ 1.1021242 ],
        [-0.8812846 ],
        [-1.0910277 ],
        [-1.0544256 ]], dtype=float32),
 array([-0.20735435], dtype=float32)]

In [123]:
y_pred=model.predict(x_test)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


array([[0.02306982],
       [0.09426511],
       [0.09251503],
       ...,
       [0.00202616],
       [0.04570076],
       [0.40977967]], dtype=float32)

In [124]:
y_pred=y_pred.argmax(axis=-1)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [125]:
from sklearn.metrics import accuracy_score

In [126]:
accuracy_score(y_test,y_pred)

0.7925

In [141]:
y_pred_train=model.predict(x_train)
y_pred_train

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


array([[0.02053389],
       [0.06560426],
       [0.6803738 ],
       ...,
       [0.56624043],
       [0.03489532],
       [0.37088025]], dtype=float32)

In [142]:
y_pred_train=y_pred_train.argmax(axis=-1)
y_pred_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [143]:
accuracy_score(y_train,y_pred_train)

0.79725