In [122]:
import numpy as np
import pandas as pd
import keras
from keras.layers import Dense
import  tensorflow as tf
from keras.models import Sequential
from sklearn.datasets import make_moons

In [124]:
X,y=make_moons(n_samples=250,noise=0.05,random_state=42)

In [126]:
X

array([[ 8.41540974e-02,  1.13341197e-01],
       [ 1.05091536e+00,  1.54710235e-01],
       [-7.16555269e-01,  6.75607887e-01],
       [ 6.09316755e-02,  9.26542340e-01],
       [-1.00552480e+00,  3.36425155e-01],
       [ 7.63045744e-01, -4.82519400e-01],
       [ 1.30067681e+00, -4.60456076e-01],
       [ 8.93997023e-01, -5.39443631e-01],
       [ 1.01492378e+00,  2.49633435e-01],
       [-8.88621081e-01,  5.38566586e-01],
       [ 1.36613788e+00, -3.56819676e-01],
       [ 1.69872955e+00, -2.50238607e-01],
       [ 1.93909982e+00,  7.98335031e-02],
       [ 1.98164910e+00,  2.73166182e-01],
       [-1.92842298e-01,  9.90722796e-01],
       [ 1.87318667e+00, -1.28604429e-01],
       [ 1.12842503e+00, -4.29068613e-01],
       [ 9.60365014e-01,  5.24004362e-01],
       [ 6.83418960e-01, -4.32057757e-01],
       [ 8.36557987e-01,  5.74232279e-01],
       [ 2.04424212e+00,  4.47864563e-01],
       [ 7.89541222e-01,  4.20628768e-01],
       [-8.99855447e-01,  3.09253977e-01],
       [-1.

In [127]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [212]:
model=Sequential()
model.add(Dense(10,activation='sigmoid',input_dim=2))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

In [214]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [216]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_56 (Dense)                     │ (None, 10)                  │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_57 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_58 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_59 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_60 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_61 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_62 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_63 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_64 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_65 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_66 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_67 (Dense)                     │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,141 (4.46 KB)

 Trainable params: 1,141 (4.46 KB)

 Non-trainable params: 0 (0.00 B)

In [218]:
old_weights=model.get_weights()[0]
old_weights

array([[ 0.5949102 ,  0.70187193,  0.50068516, -0.4234519 ,  0.13212144,
        -0.07369733,  0.02777207, -0.61908597,  0.24248701,  0.01459563],
       [ 0.6735274 ,  0.63530797, -0.25062943,  0.34560865, -0.5373802 ,
        -0.28955793,  0.3953014 , -0.01511371, -0.3394008 , -0.5699478 ]],
      dtype=float32)

In [220]:
old_weights9=model.get_weights()[9]
old_weights9

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [222]:
from sklearn.model_selection import train_test_split

In [224]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [226]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.5020 - loss: 0.6954
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5143 - loss: 0.6930
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5159 - loss: 0.6928
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5172 - loss: 0.6927
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4871 - loss: 0.6945
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5384 - loss: 0.6919
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4791 - loss: 0.6943
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5332 - loss: 0.6930
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5414 - loss: 0.6930
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5317 - loss: 0.6929
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5034 - loss: 0.6932
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4549 - loss: 0.6950
E

In [230]:
eta=model.optimizer.get_config()['learning_rate']
eta

0.0010000000474974513

In [236]:
new_weights=model.get_weights()[0]
new_weights

array([[ 0.5479403 ,  0.72140217,  0.53305924, -0.39713836,  0.16395015,
        -0.10304618,  0.02137107, -0.60004765,  0.30533254, -0.01863176],
       [ 0.7133175 ,  0.6180301 , -0.2799411 ,  0.32326758, -0.5627067 ,
        -0.26681602,  0.40058866, -0.03262958, -0.39134613, -0.54391813]],
      dtype=float32)

In [238]:
gradient=(old_weights-new_weights)/eta
gradient

array([[ 46.969887 , -19.530235 , -32.37408  , -26.313541 , -31.8287   ,
         29.348848 ,   6.4009986, -19.038319 , -62.845524 ,  33.22739  ],
       [-39.790092 ,  17.277895 ,  29.311686 ,  22.341072 ,  25.326488 ,
        -22.741913 ,  -5.2872596,  17.515871 ,  51.945328 , -26.029646 ]],
      dtype=float32)

In [244]:
abs(100*(old_weights-new_weights)/old_weights)

array([[  7.895291 ,   2.7825925,   6.465956 ,   6.214057 ,  24.090488 ,
         39.823494 ,  23.048332 ,   3.0752304,  25.917068 , 227.65305  ],
       [  5.907717 ,   2.7196095,  11.69523  ,   6.4642687,   4.7129555,
          7.8540115,   1.3375262, 115.89391  ,  15.305011 ,   4.5670233]],
      dtype=float32)

In [204]:
new_weights=model.get_weights()[0]
new_weights 

array([[-0.26737309,  0.25856015, -0.34165195, -0.0008118 ,  0.45308566,
        -0.07521887,  0.46834582, -0.0602688 , -0.19746795, -0.14991178],
       [-0.43092814,  0.68339795, -0.00131399,  0.20731686, -0.06633225,
        -0.26628453,  0.26201242,  0.35207546,  0.20205435, -0.51939327]],
      dtype=float32)

In [206]:
old_weights


array([[-0.15018725,  0.26522857, -0.18286067,  0.05130315,  0.4091726 ,
        -0.10955232,  0.4688869 ,  0.07713765, -0.05783796, -0.2537842 ],
       [-0.5401621 ,  0.61515266, -0.09599096,  0.09505242,  0.02329493,
        -0.27341738,  0.25270104,  0.26479888,  0.11643505, -0.42822495]],
      dtype=float32)

In [208]:
new_weights9=model.get_weights()[9]
new_weights9

array([-0.01623527,  0.01346446,  0.04285259,  0.05722563, -0.03733812,
       -0.00367344,  0.08103538,  0.01327766,  0.01088756, -0.00678127],
      dtype=float32)

In [210]:
old_weights9

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)